//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BektekInc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetails_Valentine
    {
        public int orderdetailId { get; set; }
        public int orderID { get; set; }
        public string Part_num { get; set; }
        public Nullable<int> Qty { get; set; }
        public decimal Price { get; set; }
    
        public virtual orderHeader_Valentine orderHeader_Valentine { get; set; }
    }
}
